### ISSUE TITLE
XMatch "Mauvaise Requête"

### ISSUE THREAD

**Issue by bsipocz** [astropy/astroquery#1376]
Consider the same example as in #1375. That query returns 2 matches. Keeping one of the matching coordinate in the input however how results in a "Bad query" response instead of the one matching result.

```
 In [3]: from astropy.table import Table
   ...: import astropy.units as u
   ...: from  astroquery.xmatch import XMatch
   ...: 
   ...: input_table=Table.read("""2.11044940645274 0.688137082702486
   ...:     2.09619379588014 0.706120900363544""", names=['ra', 'dec'], format='ascii')
   ...: 
   ...: XMatch.query(input_table, 'vizier:II/311/wise', 5*u.arcsec, 'ra', 'dec')

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-3-904fdd07e2c9> in <module>()
      6     2.09619379588014 0.706120900363544""", names=['ra', 'dec'], format='ascii')
      7 
----> 8 XMatch.query(input_table, 'vizier:II/311/wise', 5*u.arcsec, 'ra', 'dec')

~/munka/devel/astroquery/astroquery/xmatch/core.py in query(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, cache, get_query_payload)
     59         response = self.query_async(cat1, cat2, max_distance, colRA1, colDec1,
     60                                     colRA2, colDec2, cache=cache,
---> 61                                     get_query_payload=get_query_payload)
     62         if get_query_payload:
     63             return response

~/munka/devel/astroquery/astroquery/xmatch/core.py in query_async(self, cat1, cat2, max_distance, colRA1, colDec1, colRA2, colDec2, cache, get_query_payload)
     93         response = self._request(method='POST', url=self.URL, data=payload,
     94                                  timeout=self.TIMEOUT, cache=cache, **kwargs)
---> 95         response.raise_for_status()
     96 
     97         return response

/usr/local/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    937 
    938         if http_error_msg:
--> 939             raise HTTPError(http_error_msg, response=self)
    940 
    941     def close(self):

HTTPError: 400 Client Error: Mauvaise Requête for url: http://cdsxmatch.u-strasbg.fr/xmatch/api/v1/sync
```

(Here is the result with the 5 input:
```
In [4]: from astropy.table import Table
   ...: import astropy.units as u
   ...: from  astroquery.xmatch import XMatch
   ...: 
   ...: input_table=Table.read("""2.11044940645274 0.688137082702486
   ...:     2.11504231688281 0.671688214247088
   ...:     2.08882950663451 0.719216362471814
   ...:     2.09308610414763 0.708799922876203
   ...:     2.09619379588014 0.706120900363544""", names=['ra', 'dec'], format='ascii')
   ...: 
   ...: XMatch.query(input_table, 'vizier:II/311/wise', 5*u.arcsec, 'ra', 'dec')
   ...: 
WARNING: W47: None:94:3: W47: Missing arraysize indicates length 1 [astropy.io.votable.converters]
WARNING: W32: None:35:3: W32: Duplicate ID 'ra' renamed to 'ra_2' to ensure uniqueness [astropy.io.votable.tree]
WARNING: W32: None:37:3: W32: Duplicate ID 'dec' renamed to 'dec_2' to ensure uniqueness [astropy.io.votable.tree]
WARNING: W33: None:35:3: W33: Column name 'ra' renamed to 'ra 2' to ensure uniqueness [astropy.io.votable.tree]
WARNING: W33: None:37:3: W33: Column name 'dec' renamed to 'dec 2' to ensure uniqueness [astropy.io.votable.tree]
Out[4]: 
<Table masked=True length=2>
angDist         ra               dec               JNAME          ra_2   ... cc_flags ext_flg var_flg ph_qual r_2mass
 arcsec                                                           deg    ...                                         
float64      float64           float64            bytes19       float64  ...  bytes4   bytes1  bytes4  bytes4 float32
-------- ---------------- ----------------- ------------------- -------- ... -------- ------- ------- ------- -------
 0.16796 2.11044940645274 0.688137082702486 J000826.51+004117.4 2.110478 ...     0000       0    10nn    AAUU   0.256
0.537585 2.08882950663451 0.719216362471814 J000821.29+004308.8 2.088721 ...     0000       0    00nn    AAUU   0.534
```

**Comment by bsipocz** [comment]
This seems to be the same as the previous #968 issue. Did you @keflavich end up reporting it upstream?

**Comment by keflavich** [comment]
No, I don't think I did because I ended up finding a different error.

**Comment by fxpineau** [comment]
I am discovering this thread (thanks to @tboch).
FYI, the bug was on the server side, due to CSV/ASCII input files containing only one or two data rows.
A user mentioned it on the CDS hotline (providing the returned VOTable containing the error stack trace) and I fixed it a week ago (on Match, 7).

**Comment by keflavich** [comment]
Thanks @fxpineau!  @bsipocz , could you confirm and then close this?

**Comment by bsipocz** [comment]
As I recall I run into it during class again on Monday, but will check it more carefully again.

**Comment by bsipocz** [comment]
I still get the same 400 Error when running the example above. (cache has been cleared, but it made no difference).

**Comment by fxpineau** [comment]
With @tboch, we just tested using the current version of astropy and astroquery. We first obtained an error due to the names 'ra' and 'dec' (are you using a patched version?). But renaming in e.g. 'ra1' and 'ra2', and submitting only two rows, we successfully obtain a result containing a single row.
In case of error, you obtain a VOTable containing a stack trace. It would be useful if you could provide it.

**Comment by bsipocz** [comment]
yes, renaming the column works, and in a few cases it also helped to change the catalog to `'vizier:II/328/allwise'`. 
We'll patch the column name clashes eventually in #1375, I just haven't got back to it yet.

**Comment by bsipocz** [comment]
I'm closing this in favour of #1465 that tracks the need for parsing the VOTable for error trace.
